version: "3.1"

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: always
        environment:
        - MONGO_INITDB_ROOT_USERNAME=shapelabAdmin
        - MONGO_INITDB_ROOT_PASSWORD=shapelabPassword
        - MONGO_INITDB_DATABASE=shapelab
        volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro 
        - ./db:/data/db
        ports: 
        - "27017:27017"
    app:
        container_name: app
        restart: always
        build: .
        ports: 
        - "8080-8081:8080-8081"
        links:
        -  mongo

